### ISSUE TITLE
Can't Run BrainWorkshop on Arch Linux

### ISSUE THREAD

**Issue by Alchemek** [brain-workshop/brainworkshop#41]
Hello,

I used to have BrainWorkshop working on Linux, but now, after it's been several months (maybe even a year or two), it isn't working anymore. I decided to fetch the latest copy and follow the latest instructions, but I can't seem to get it to work even so.

The following is the data I have collected for your reference:

[alchemek@### brainworkshop-master]$ ls -l
total 280
-rw-r--r--  1 alchemek alchemek  17895 Nov 28 02:19 LICENSE.md
-rw-r--r--  1 alchemek alchemek   7783 Nov 28 02:19 Readme-instructions.txt
-rw-r--r--  1 alchemek alchemek   2320 Nov 28 02:19 Readme-resources.txt
-rw-r--r--  1 alchemek alchemek  19156 Nov 28 02:19 Readme.md
-rw-r--r--  1 alchemek alchemek   1016 Nov 28 02:19 appveyor.yml
-rw-r--r--  1 alchemek alchemek    197 Nov 28 02:19 brainworkshop.desktop
-rw-r--r--  1 alchemek alchemek 191805 Nov 28 02:19 brainworkshop.py
drwx------  2 alchemek alchemek   4096 Nov 28 02:19 data
drwx------  9 alchemek alchemek   4096 Nov 29 22:28 future
drwx------  3 alchemek alchemek   4096 Nov 29 22:28 libfuturize
drwx------  6 alchemek alchemek   4096 Nov 29 22:28 past
drwxr-xr-x 10 alchemek alchemek   4096 Mar 20 18:30 pyglet
-rw-r--r--  1 alchemek alchemek     30 Nov 28 02:19 requirements.txt
drwx------  7 alchemek alchemek   4096 Nov 28 02:19 res
drwx------  2 alchemek alchemek   4096 Nov 28 02:19 tools

[alchemek@### brainworkshop-master]$ python brainworkshop.py
No suitable audio driver could be loaded.
Full text of error:
Traceback (most recent call last):
  File "/home/alchemek/Apps/brainworkshop-master/brainworkshop.py", line 922, in <module>
    import pyglet.media
  File "/usr/lib/python3.10/site-packages/pyglet/media/__init__.py", line 143, in <module>
    add_default_media_codecs()
  File "/usr/lib/python3.10/site-packages/pyglet/media/codecs/__init__.py", line 102, in add_default_media_codecs
    if have_ffmpeg():
  File "/usr/lib/python3.10/site-packages/pyglet/media/codecs/__init__.py", line 118, in have_ffmpeg
    from . import ffmpeg_lib
  File "/usr/lib/python3.10/site-packages/pyglet/media/codecs/ffmpeg_lib/__init__.py", line 36, in <module>
    from .libavcodec import *
  File "/usr/lib/python3.10/site-packages/pyglet/media/codecs/ffmpeg_lib/libavcodec.py", line 46, in <module>
    from . import libavutil
  File "/usr/lib/python3.10/site-packages/pyglet/media/codecs/ffmpeg_lib/libavutil.py", line 206, in <module>
    avutil.av_frame_get_best_effort_timestamp.restype = c_int64
  File "/usr/lib/python3.10/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/libavutil.so.57: undefined symbol: av_frame_get_best_effort_timestamp
Exception ignored in atexit callback: <function _delete_audio_driver at 0x7f115114e440>
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pyglet/media/drivers/__init__.py", line 102, in _delete_audio_driver
    from .. import Source
  File "/usr/lib/python3.10/site-packages/pyglet/media/__init__.py", line 143, in <module>
    add_default_media_codecs()
  File "/usr/lib/python3.10/site-packages/pyglet/media/codecs/__init__.py", line 102, in add_default_media_codecs
    if have_ffmpeg():
  File "/usr/lib/python3.10/site-packages/pyglet/media/codecs/__init__.py", line 118, in have_ffmpeg
    from . import ffmpeg_lib
  File "/usr/lib/python3.10/site-packages/pyglet/media/codecs/ffmpeg_lib/__init__.py", line 36, in <module>
    from .libavcodec import *
  File "/usr/lib/python3.10/site-packages/pyglet/media/codecs/ffmpeg_lib/libavcodec.py", line 46, in <module>
    from . import libavutil
  File "/usr/lib/python3.10/site-packages/pyglet/media/codecs/ffmpeg_lib/libavutil.py", line 206, in <module>
    avutil.av_frame_get_best_effort_timestamp.restype = c_int64
  File "/usr/lib/python3.10/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/libavutil.so.57: undefined symbol: av_frame_get_best_effort_timestamp

Any ideas?

**Comment by xantares** [comment]
yes, pyglet is broken with ffmpeg 5:
https://github.com/pyglet/pyglet/issues/541
this already has been reported to arch also:
https://bugs.archlinux.org/task/74044?project=5&string=python-pyglet
I close the bug here as its not a bw bug in itself
