### ISSUE TITLE
Crashes when entering 'choose game mode'

### ISSUE THREAD

**Issue by addeps3** [brain-workshop/brainworkshop#49]
This is similar to issue #48 

(For some reason, github removes the line-breaks in the output, so I removed the code-brackets.)

log:
./brainworkshop.py
Traceback (most recent call last):
  File "/home/user/Downloads/brainworkshop-master/./brainworkshop.py", line 4820, in <module>
    pyglet.app.run()
  File "/usr/lib/python3.10/site-packages/pyglet/app/__init__.py", line 107, in run
    event_loop.run(interval)
  File "/usr/lib/python3.10/site-packages/pyglet/app/base.py", line 187, in run
    timeout = self.idle()
  File "/usr/lib/python3.10/site-packages/pyglet/app/base.py", line 248, in idle
    self.clock.call_scheduled_functions(dt)
  File "/usr/lib/python3.10/site-packages/pyglet/clock.py", line 262, in call_scheduled_functions
    item.func(now - item.last_ts, *item.args, **item.kwargs)
  File "/usr/lib/python3.10/site-packages/pyglet/app/base.py", line 154, in _redraw_windows
    window.dispatch_event('on_draw')
  File "/usr/lib/python3.10/site-packages/pyglet/window/__init__.py", line 1363, in dispatch_event
    super().dispatch_event(*args)
  File "/usr/lib/python3.10/site-packages/pyglet/event.py", line 415, in dispatch_event
    if handler(*args):
  File "/home/user/Downloads/brainworkshop-master/./brainworkshop.py", line 4646, in on_draw
    graph.draw()
  File "/home/user/Downloads/brainworkshop-master/./brainworkshop.py", line 1590, in draw
    self.create_batch()
  File "/home/user/Downloads/brainworkshop-master/./brainworkshop.py", line 1622, in create_batch
    self.batch.add(3, pyglet.gl.GL_LINE_STRIP,
AttributeError: 'Batch' object has no attribute 'add'

pip is version: 

` pip install pyglet
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pyglet in /usr/lib/python3.10/site-packages (2.0.1)
`

distro is Manjaro

**Comment by addeps3** [comment]
Thanks so much! Can live out my dreams now
