### ISSUE TITLE
Error: unable to load pyglet when >pyglet-2.0.15

### ISSUE THREAD

**Issue by majsterElektron** [brain-workshop/brainworkshop#59]
I am getting the following error running with python3.11 and pyglet version greater than 2.0.15. Tested on 2.0.17 and 2.0.18.   
2.0.15 runs fine.

```
Error: unable to load pyglet.  If you already installed pyglet, please ensure ctypes is installed.  Please visit http://pyglet.org
Full text of error:
Traceback (most recent call last):
  File "/usr/bin/brainworkshop", line 915, in <module>
    if NOVBO: pyglet.options['graphics_vbo'] = False
              ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pyglet/__init__.py", line 267, in __setitem__
    assert key in self.__annotations__, f"Invalid option name: '{key}'"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Invalid option name: 'graphics_vbo'
```

**Comment by vymague** [comment]
Same problem. Anyone got a solution or alternative program?

**Comment by notevenaperson** [comment]
You've been notified to try out the version in #60, if you still care.

**Comment by notevenaperson** [comment]
You've been notified to try my version, if you still care.

**Comment by xantares** [comment]
try master
